// Code generated by command: go run asm.go -pkg jsonstr -out escape_amd64.s -stubs escape_amd64.go. DO NOT EDIT.

package jsonstr

func UnescapeAVX(dst []byte, src []byte) int

func UnescapeSSE(dst []byte, src []byte) int

func UnescapeNaive(dst []byte, src []byte) int
